parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TicTacToe\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    TicTacToe\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    TicTacToe\Service\:
        resource: '../src/Service'
        public: true

    TicTacToe\Factory\:
        resource: '../src/Factory'
        public: true

    TicTacToe\EventListener\ExceptionSubscriber:
        class: TicTacToe\EventListener\ExceptionSubscriber
        arguments: []
        tags:
            - { name: kernel.event_subscriber }
