parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    TicTacToe\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'
    TicTacToe\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']